# Generated by Django 5.2.6 on 2025-09-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_clinicreport'),
        ('data_collection', '0007_remove_clinicreport_id_clinicreport_report_id'),
    ]

    operations = [
    ]
