# Generated by Django 5.2.6 on 2025-09-28 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0008_merge_20250928_1514'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicreport',
            name='clinic_user',
        ),
        migrations.RemoveField(
            model_name='clinicreport',
            name='district',
        ),
        migrations.RemoveField(
            model_name='clinicreport',
            name='state',
        ),
        migrations.AddField(
            model_name='clinicreport',
            name='clinic',
            field=models.ForeignKey(blank=True, db_column='clinic_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicreport',
            name='cholera_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clinicreport',
            name='deaths_reported',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clinicreport',
            name='diarrhea_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clinicreport',
            name='fever_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clinicreport',
            name='hospitalized_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clinicreport',
            name='typhoid_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clinicreport',
            name='village',
            field=models.ForeignKey(db_column='village_id', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reports', to='data_collection.village'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='village',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='village_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='village',
            name='district_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='state_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddIndex(
            model_name='clinicreport',
            index=models.Index(fields=['village'], name='data_collec_village_175716_idx'),
        ),
        migrations.AlterModelTable(
            name='clinicreport',
            table='data_collection_clinicreport',
        ),
    ]
